server:
  port: 8082
  servlet:
    context-path: /PhoneBook

# datasource configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:testdb
    username: sa
#Hibernate Configuration
  jpa:
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

    defer-datasource-initialization: true
 
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
